### ISSUE TITLE
camelCase column names in bigquery break copies

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#100] opened 2020-02-04 01:09 UTC
If you have a camelCase column name, you will get an error like:

```
Error: could not find column subscriptionpayment in BigQuery table myproject-123:mydataset.myorders
```

I assume this is because it is treating column names as case-insensitive but they really aren't

**Comment by seamusabshere** [comment] 2020-03-23 01:19
finding more examples of this

**Comment by emk** [comment] 2020-03-25 22:13
Duplicate of #84.

**Closed by emk** 2020-03-25 22:13 UTC
Labels: bug, faraday
