### ISSUE TITLE
can't upsert into postgres table with legacy json columns

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#85] opened 2019-12-11 15:50 UTC
you will get a

```
db error: ERROR: unsupported jsonb version number 123
```

**Comment by emk** [comment] 2019-12-11 15:55
The problem is [here](https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbarlib/src/drivers/postgres/write_local_data.rs#L247-L255):

```rust
    // Connect to PostgreSQL and prepare our destination table.
    let mut client = connect(ctx.clone(), url.clone()).await?;
    prepare_table(&ctx, &mut client, dest_table.clone(), &if_exists).await?;

    // Look up our actual destination table, which has either existed all along,
    // or which we just created.
    let mut real_dest_table =
        PgCreateTable::from_pg_catalog(dest.url(), dest.table_name())?;
    real_dest_table = real_dest_table.aligned_with(&dest_table)?;
```

We can correctly handle legacy `json` columns if we're not using upsert, because we fetch `real_dest_table` out of the database and use _that_, which allows us to distinguish between `json` and `jsonb`.

But upserts are configured inside `prepare_table`, which can't assume that we actually have a database table yet, and so they use `dest_table` instead of `real_dest_table` to create the temporary table.

There's a relatively small fix for this, but it requires a bunch of gross special-casing.

The underlying issue is that `dbcrossbar` refuses to think in terms of weird database-specific column types, and it would really prefer for you to use portable, sensible types like `jsonb`. Certain drivers, like the `postgres` driver, know how to handle _existing_ columns with certain non-portable types, but they don't know how to create those columns. And this breaks those use cases which require temporary tables.

Ick.

**Closed** 2019-12-31 22:13 UTC
Labels: bug
